### ISSUE TITLE
print and urllib2 problem

### ISSUE THREAD

**Issue by twofund** [singh47/website-autovisitor#1]
when i try to run code 
its give an error for print.
when i fix it its give enother error for module not found for urllib2 

what i missed ?

**Comment by singh47** [comment]
Hi @twofund you are tyring this code with python3. It is python2 compatible till now.
Please try to run it as:
python2 autovisitor.py
(you probably have both versions of python installed)

**Comment by hustle-coin** [comment]
import urllib.request as urllib2
