### ISSUE TITLE
    print self.con_total,"total connections, success = ",self.con_sucess," failed= ",self.con_failed           ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.con_total,"total connections, success = ",self.con_sucess," failed= ",self.con_failed)?

### ISSUE THREAD

**Issue by arjboy** [singh47/website-autovisitor#3]
print self.con_total,"total connections, success = ",self.con_sucess," failed= ",self.con_failed
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.con_total,"total connections, success = ",self.con_sucess," failed= ",self.con_failed)?

**Comment by hustle-coin** [comment]
it gives you the answer right there, print(self.con_total,"total connections, success = ",self.con_sucess," failed= ",self.con_failed)

**Comment by singh47** [comment]
Thanks @hustle-coin , @arjboy this code is compatible with python2.7 
from the issue above; it seems that you are trying it with python3, as the print statement needs parenthesis in Python 3.

e.g:

print("Hello")    # syntax for python3
print "Hello"     # syntax for python2
